# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'samplegui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(757, 460)
        Dialog.setStyleSheet("QDialog{\n"
"background-color: pink;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.Browse = QtWidgets.QPushButton(Dialog)
        self.Browse.setObjectName("Browse")
        # connect the browse button to the browse function
        self.Browse.clicked.connect(self.browse)
        self.gridLayout.addWidget(self.Browse, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.Run = QtWidgets.QPushButton(Dialog)
        self.Run.setObjectName("Run")
        # connect the run button to the code function
        self.Run.clicked.connect(self.code)
        self.gridLayout.addWidget(self.Run, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Browse.setText(_translate("Dialog", "Browse"))
        self.Run.setText(_translate("Dialog", "Run"))

    def browse(self):
        # get the path of the python script
        path = QtWidgets.QFileDialog.getOpenFileName()[0]
        # set the path in the lineEdit
        self.lineEdit.setText(path)
    
    def code(self):
        path = self.lineEdit.text()
        # run the python script and get the output in the variable using subprocess
        output = subprocess.check_output(['python', path])
        # convert the output from bytes to string
        output = output.decode('utf-8')
        # set the output in the textEdit
        self.textEdit.setText(output)
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
